Repository W00jo/LemJem, pull requests merged in 2024-12, with the labels that each got.

#18 Fix diagonal movement speed
  scripts/player_fp.gd
Labels: bug

#17 Asset Robocika
  assets/3d/textures/ziutek_paleta_barw.webp
  assets/3d/textures/ziutek_paleta_barw.webp.import
  assets/3d/ziutek.blend1
  assets/3d/ziutek.glb
  assets/3d/ziutek.glb.import
Labels: enhancement

#19 Deleted two files, edited one
  Maska.csproj
  scenes/grid/BattleScene.cs
  scripts/projectiles.cs
Labels: duplicate

#20 Enemy behavior
  scenes/grid/enemy_battle.gd
  scripts/player_fp.gd
Labels: enhancement
